version: '3.7'
services:
    postgres:
        image: postgres:11
        environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
        ports:
          - "5432:5432"
    airflow:
        image: local-airflow:2.0.0
        restart: always
        depends_on:
            - postgres
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
